## pytorch数据操作笔记

1. tensor(张量）概念
  张量是神经网络使用的最主要数据结构，形式上类似n维数组,张量支持CPU、GPU上的异步计算，并支持自动微分，具体属性如下：
   - rank：需要多少个索引来访问张量种的数据元素
   - length of axis: 每个张量轴的长度，类似数组最大长度
   - shape: 类似m*n矩阵表示法
2. tensor构建常用方法

In [4]:
import torch as t 

x= t.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

arange 函数会默认产生从0开始的n个连续的整数，并把他们存在一个x的向量里

In [5]:
x.shape # 查看tensor的shape

torch.Size([12])

In [9]:
x=x.reshape((3,4)) # 重置张量的shape
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
x= x.reshape((2,-1)) # 当张量rank为2时，只要输入一个维度指定长度，另一个可以用-1替换
x

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [12]:
t.empty(2,3) # 随机获取内存的数值构建张量

tensor([[2.1456e-07, 1.0027e-11, 5.3772e+22],
        [2.1629e+23, 1.7565e-04, 6.3013e-10]])

In [13]:
t.zeros(3,3) # 初始化张量全0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
t.ones(2,3,4) # 初始化张量全1

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [16]:
t.Tensor([[1,2,3],[2,3,4]]) # 将指定python列表转换为张量

tensor([[1., 2., 3.],
        [2., 3., 4.]])

In [17]:
t.randn(2,3) # 获得的随机张量数值是标准正态分布的可能取值

tensor([[ 0.7161,  0.3105, -0.2103],
        [ 0.2853,  0.5238, -1.7068]])

3. tensor常用计算

In [22]:
x = t.Tensor([1,2,3])
y = t.ones_like(x)*10  # 初始化和x一样张量，*n会把所有元素都变成n
y

tensor([10., 10., 10.])

In [23]:
x+y,x*y,x-y,x/y,x**y

(tensor([11., 12., 13.]),
 tensor([10., 20., 30.]),
 tensor([-9., -8., -7.]),
 tensor([0.1000, 0.2000, 0.3000]),
 tensor([1.0000e+00, 1.0240e+03, 5.9049e+04]))

In [24]:
t.exp(x) # 对每个元素进行e求幂

tensor([ 2.7183,  7.3891, 20.0855])

In [26]:
x = t.Tensor([[1,2,3],[2,3,4]])
y = t.ones_like(x)*2
x+y,x*y,x-y,x/y,x**y # 这里运算跟矩阵的不一样，都是对应元素做正常加减乘除

(tensor([[3., 4., 5.],
         [4., 5., 6.]]),
 tensor([[2., 4., 6.],
         [4., 6., 8.]]),
 tensor([[-1.,  0.,  1.],
         [ 0.,  1.,  2.]]),
 tensor([[0.5000, 1.0000, 1.5000],
         [1.0000, 1.5000, 2.0000]]),
 tensor([[ 1.,  4.,  9.],
         [ 4.,  9., 16.]]))

In [37]:
y = t.Tensor([[1,2,3],[2,3,4],[3,4,5],[5,6,7]])
# y.t()  #  这里是矩阵操作，求张量转置
x= t.arange(12,dtype=torch.float32).reshape(3,-1) # dtype=torch.float32必须加上，不然会报类型不一致错误
t.mm(x,y)  # 这里是矩阵的乘法操作

tensor([[ 23.,  29.,  35.],
        [ 67.,  89., 111.],
        [111., 149., 187.]])

In [44]:
t.cat((x,y.t()),dim=1) # 矩阵合并操作，dim指定合并维度，0按行，1按列，两个张量必须同型才能执行合并操作

tensor([[ 0.,  1.,  2.,  3.,  1.,  2.,  3.,  5.],
        [ 4.,  5.,  6.,  7.,  2.,  3.,  4.,  6.],
        [ 8.,  9., 10., 11.,  3.,  4.,  5.,  7.]])

In [46]:
x==y.t() # 对同型张量的同位置的数据进行比较，返回的张量对应比较结果，相同为True,不同为False

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [47]:
x.sum() # 对张量里所有元素求和

tensor(66.)

4.广播机制

  当两个张量的形状不同时，可以使用类似NumPy的广播机制：首先适当地复制元素，使两个张量具有相同的形状，然后按元素进行操作。

In [49]:
a = torch.arange(3, dtype=torch.float).reshape((3, 1))
b = torch.arange(2, dtype=torch.float).reshape((1, 2))
a+b

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

因为a和b分别是（3x1）和（1x2）矩阵，所以如果我们要将它们相加，它们的形状就不匹配。Pythorch通过将两个矩阵的条目“广播”到一个更大的（3x2）矩阵中来解决这个问题，如上所示：对于矩阵a，它复制列，对于矩阵b，它在将两个元素相加之前复制行。

5. 切片和索引机制

In [52]:
x= t.arange(12).reshape(3,-1)
x[1:]   # 是按行切片的

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [53]:
x[2,2] # 对相应的下表元素操作

tensor(10)

In [55]:
x[0:1,:]=12
x             # 给指定行赋相同的值[0:n,:]

tensor([[12, 12, 12, 12],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

6. 节省内存

   在前面的示例中，每次运行操作时，我们都会分配新内存来承载其结果。例如，如果我们写y=x+y，我们将取消引用y用来指向的矩阵，而将它指向新分配的内存。在下面的示例中，我们用Python的id（）函数来演示这一点，该函数给出了被引用对象在内存中的确切地址。运行y=y+x之后，我们将发现id（y）指向另一个位置。这是因为Python首先计算y+x，为结果分配新的内存，然后将y重定向到内存中的这个新位置。
   - 定义一个相同类型的张量z,使用z[:]接收结果
   - 使用运算的内置方法替换符号，并通过out参数指定结果指向
   - 若x不参与后续运算，使用x+=y来直接覆盖
 

7. torch和numpy转换

In [56]:
a = x.numpy()
print(type(a))
b = torch.tensor(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


8. 练习

1. 

In [61]:
x= t.arange(12,dtype=torch.float32).reshape(3,-1)
y = t.Tensor([[1,2,3],[2,3,4],[3,4,5],[5,6,7]]).t()
x<y

tensor([[ True,  True,  True,  True],
        [False, False, False, False],
        [False, False, False, False]])

2.

In [67]:
z = t.ones(3,3)
id1 =id(z)
z+=t.mm(x,y.t())
z

tensor([[ 24.,  30.,  36.],
        [ 68.,  90., 112.],
        [112., 150., 188.]])