## 线性代数操作

1. 标量

In [3]:
import torch as t

x = t.tensor(3.0)
y = t.tensor(4.0)
x+y,x-y,x*y,x/y

(tensor(7.), tensor(-1.), tensor(12.), tensor(0.7500))

2. 向量

In [5]:
a = t.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
len(a) # 张量长度

12

3. 矩阵

In [7]:
A = t.arange(12).reshape(3,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
A.t()

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [9]:
A.T # 另一种转置方式

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [12]:
B= t.arange(9).reshape(3,3)
B==B.T  # 返回比较矩阵，必须是同型才可以

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

3. 矩阵计算

In [17]:
A = t.arange(20, dtype=t.float32).reshape(5, 4)
B = A.clone()  # Assign a copy of `A` to `B` by allocating new memory
A,B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]))

In [18]:
a=2
a+A # 标量和矩阵相加不会改变矩阵形状，而是与每个矩阵元素相加减

tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])

In [20]:
c= t.arange(6)
c.sum(),A.sum() #对向量和矩阵所有元素求和

(tensor(15), tensor(190.))

In [21]:
A_sum_axis0 = A.sum(axis=0) # 计算列的元素和，返回是向量
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [22]:
A_sum_axis0 = A.sum(axis=1)  # 计算行的和
A_sum_axis0, A_sum_axis0.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [25]:
A.sum(axis=[0, 1]) # 等价.sum() ,axis=[]只能取-2，1的数

tensor([ 6., 22., 38., 54., 70.])

In [26]:
A.numel() # 获取矩阵元素个数

20

In [27]:
sum_A = A.sum(axis=1, keepdims=True) # 这样计算求和等到的是原矩阵维度的结果
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [28]:
A.cumsum(axis=0) # 比如A[1][2]数值是A[1][1]+A[1][2](这里用数学表达)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [33]:
x = t.arange(4,dtype = t.float32)
y = t.ones(4,dtype = t.float32)
t.dot(x,y) # 元素必须是浮点数才行

tensor(6.)

In [34]:
x.norm()  # 对向量x求模

tensor(3.7417)

In [35]:
x.abs().sum() # 对x取1阶范式（每个元素绝对值的和）

tensor(6.)

In [36]:
A.norm() # 矩阵求范式

tensor(49.6991)